DROP DATABASE IF EXISTS DBSISTEMAAVISOS;
CREATE DATABASE DBSISTEMAAVISOS;

USE DBSISTEMAAVISOS;

CREATE TABLE TIPOUSUARIO (
IDTIPOUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, DESCRICAO VARCHAR(255)
);

CREATE TABLE USUARIO (
IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, IDTIPOUSUARIO INT, FOREIGN KEY (IDTIPOUSUARIO) REFERENCES TIPOUSUARIO (IDTIPOUSUARIO)
, NOME VARCHAR(255)
, CPF CHAR(11)
, EMAIL VARCHAR(255)
, LOGIN VARCHAR(255)
, SENHA VARCHAR(255)
);

CREATE TABLE AVISO (
IDAVISO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, IDUSUARIO INT, FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
, DATACADASTRO DATE
, DATAEXPIRACAO DATE
);

CREATE TABLE AVISOESTAGIO (
IDAVISOESTAGIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, IDAVISO INT, FOREIGN KEY (IDAVISO) REFERENCES AVISO (IDAVISO)
, EMPRESA VARCHAR(255)
, TELEFONE CHAR(11)
, EMAIL VARCHAR(255)
, CARGO VARCHAR(255)
, JORNADA INTEGER(2)
, REMUNERACAO DECIMAL(10,2)
);

CREATE TABLE AVISOCURSOLIVRE (
IDAVISOCURSOLIVRE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, IDAVISO INT, FOREIGN KEY (IDAVISO) REFERENCES AVISO (IDAVISO)
, NOME VARCHAR(255)
, PUBLICOALVO VARCHAR(255)
, REQUISITO VARCHAR(255)
, AMBIENTE VARCHAR(255)
, DATACURSO DATE
, VALOR DECIMAL(10,2)
);

CREATE TABLE AVISOCOORDENACAO (
IDAVISOCOORDENACAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, IDAVISO INT, FOREIGN KEY (IDAVISO) REFERENCES AVISO (IDAVISO)
, DESCRICAO VARCHAR(255)
);

INSERT INTO TIPOUSUARIO (descricao) VALUES ('ADMINISTRADOR');
INSERT INTO TIPOUSUARIO (descricao) VALUES ('COORDENADOR');
INSERT INTO TIPOUSUARIO (descricao) VALUES ('SECRETARIA');
INSERT INTO TIPOUSUARIO (descricao) VALUES ('ALUNO');


SELECT * FROM USUARIO;


INSERT INTO USUARIO VALUES(DEFAULT, 1, "gustavo", "09630985942", "PROG.GUSTAVOSANTOS@GMAIL.COM", "GUSTAVO", "ASDF1234F");


